config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :home, only: [:show, :public_locations]
  resources :user_locations, only: :create
  root 'home#show'
  get '/:user_name', to: 'home#public_locations'
end

app/models/shared_user_location.rb
class SharedUserLocation < ActiveRecord::Base
  belongs_to :user
  belongs_to :user_location

  scope :location, -> (user) { where(user_id: user.id).map{ |u| [u.user_location.latitude, u.user_location.longitude] }}
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable

  has_many :user_locations
  has_many :friends, class_name: "User", foreign_key: "friend_id"

  belongs_to :friend, class_name: "User"
end

app/models/user_location.rb
class UserLocation < ActiveRecord::Base
  belongs_to :user
  has_many :shared_user_locations
  
  scope :public_locations, -> { where(public: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :choose_layout
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :authenticate_user!,        if: :devise_controller?

  protected
  def choose_layout
    return false if request.xhr?
    return params[:layout] if params[:layout].present?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u|
      u.permit(:password, :password_confirmation, :current_password, :name, :email)
    }

    devise_parameter_sanitizer.for(:sign_up) { |u|
      u.permit(:name, :email, :password, :password_confirmation)
    }
  end

  def after_sign_in_path_for(user)
    default_redirect_path = root_path
    stored_location_for(resource) || default_redirect_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_filter  :get_location, only: [:show]

  def show  
  end

  def public_locations
    @user = User.find_by(user_name: params[:user_name])

    unless @locations = @user.try(:user_locations).try(:public_locations).try(:pluck, :latitude, :longitude)
      redirect_to root_path
    end
  end
  
  private

  def get_location
    @locations = []

    if current_user.present?
      @locations =  current_user.user_locations.pluck(:latitude, :longitude) + SharedUserLocation.includes(:user_location).location(current_user)
    end
  end
end

app/controllers/user_locations_controller.rb
class UserLocationsController < ApplicationController
  def create
  	is_public = params[:user_ids].nil? ? true : false
    if user_location = current_user.user_locations.create(latitude: request.location.latitude, longitude: request.location.longitude, public: is_public)
      params[:user_ids].try(:each) do |id|
        user_location.shared_user_locations.create(user_id: id)
      end
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_locations_helper.rb
module UserLocationsHelper
end

app/views/home/public_locations.html.erb
<h5>Public locations shared by <%= @user.user_name || @user.email %></h5>
<%= content_tag "div", id: "map", class: "map", data: { location: @locations } do %>
  <div id="popup"></div>
<% end %>

app/views/home/show.html.erb
<% unless current_user.present? %>
  <h1 class="text-center" style="margin-top: 11%;">
    <%= link_to "Login to share locations", new_user_session_path, class: "btn btn-primary btn-lg", data: {remote_modal: true} %>
  </h1>

<% else %><br/>
  <div class="row">
    <div class="text-center form-inline">
      <%= form_tag user_locations_path, :method => 'post', class: 'search-form' do  %>
        <%= select_tag :user_ids, options_from_collection_for_select(current_user.friends.order('email asc'), "id", "email"), { prompt: "--select friends--", multiple: true, class:"multiselect" } %>
        <%= submit_tag 'Share', class: "btn btn-success" %>
      <% end %>
    <h6 class="text-center"> * Select your friends to share your current location with friends or without selecting any friends to share your current location publicly.</h6>
    </div>
  </div>

  <%= content_tag "div", id: "map", class: "map", data: { location: @locations } do %>
    <div id="popup"></div>
  <% end %>
  <br/><br/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocationShare</title>
    <meta charset="utf-8">
    <script src="http://openlayers.org/en/v3.2.1/build/ol.js"></script>
    <link rel="stylesheet" href="http://openlayers.org/en/v3.2.1/css/ol.css" type="text/css">
    <script src="http://openlayers.org/en/v3.2.1/resources/jquery.min.js"></script>
    <script src="http://openlayers.org/en/v3.2.1/resources/bootstrap/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://openlayers.org/en/v3.2.1/resources/bootstrap/css/bootstrap.min.css" type="text/css">
    <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'navs/main' %>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <footer>
      <%= render 'navs/footer' %>
    </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/navs/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
	<div class="container-fluid">
		<div class="row">
	    <div class="col-lg-12">
	      <p>Copyright &copy; Piyush Awasthi 2016</p>
	    </div>
		</div>
	</div>
</div>

app/views/navs/_main.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="pull-left">
        <a class="navbar-brand logo" href="/">Location Share</a>
      </div>
      <div class="pull-right">
        <% if current_user %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Login", new_user_session_path, data: {remote_modal: true, title: "Login"} %> |
          <%= link_to "Sign up", new_user_registration_path, data: {remote_modal: true, title: "Sign up"} %>
        <% end %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
    </div>
  </div>
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>